/* GENERATED by `npm run media`. */
export const AVAILABLE: string[] = ["interior","numbers","jaali","dawn","cta"];
export const DIMS: Record<string, [number, number]> = {"interior":[920,520],"numbers":[1619,971],"jaali":[600,750],"cta":[2000,1333]};
