#!/usr/bin/env node
/* Optimises photos/videos in media-src/ (named by slot id) and switches the slots on. */
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import sharp from 'sharp';
import ffmpeg from 'ffmpeg-static';

const ROOT = process.cwd(), SRC = path.join(ROOT, 'media-src'), PUB = path.join(ROOT, 'public');
const slots = JSON.parse(await fs.readFile(path.join(ROOT, 'data/media.slots.json'), 'utf8'));
const run = (args) => new Promise((res, rej) => { const p = spawn(ffmpeg, args, { stdio: ['ignore', 'ignore', 'pipe'] }); let err = ''; p.stderr.on('data', (d) => { err = (err + d).slice(-2000); }); p.on('close', (c) => (c === 0 ? res() : rej(new Error(err)))); });
const exists = async (f) => { try { await fs.access(f); return true; } catch { return false; } };

await fs.mkdir(SRC, { recursive: true });
await fs.mkdir(path.join(PUB, 'media'), { recursive: true });
const files = await fs.readdir(SRC);
const available = [], dims = {};
for (const s of slots) {
  const out = path.join(PUB, s.file);
  const input = files.find((f) => path.parse(f).name === s.id);
  if (!input) { if (await exists(out)) available.push(s.id); continue; }
  const inPath = path.join(SRC, input);
  try {
    if (s.kind === 'image') {
      const info = await sharp(inPath).rotate().resize({ width: 2000, withoutEnlargement: true }).jpeg({ quality: 80, mozjpeg: true }).toFile(out);
      dims[s.id] = [info.width, info.height];
      console.log(`  ✓ ${s.id} (${info.width}×${info.height})`);
    } else {
      await run(['-y', '-i', inPath, '-t', '12', '-vf', 'scale=-2:720', '-c:v', 'libx264', '-preset', 'slow', '-crf', '28', '-an', '-movflags', '+faststart', '-pix_fmt', 'yuv420p', out]);
      await run(['-y', '-ss', '1', '-i', inPath, '-frames:v', '1', '-vf', 'scale=-2:720', '-q:v', '3', path.join(PUB, s.poster)]);
      console.log(`  ✓ ${s.id} (720p, 12 s max, poster)`);
    }
    available.push(s.id);
  } catch (e) { console.warn(`  ✗ ${s.id}: ${String(e.message).split('\n')[0]}`); }
}
await fs.writeFile(path.join(ROOT, 'data/media.available.ts'), `/* GENERATED by \`npm run media\`. */
export const AVAILABLE: string[] = ${JSON.stringify(available)};
export const DIMS: Record<string, [number, number]> = ${JSON.stringify(dims)};
`);
console.log(`\n${available.length} slot(s) ready. Restart \`npm run dev\` if it is running.`);
